# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://will-henney.github.io/wcsfile/"

git_url = "https://github.com/will-henney/wcsfile/tree/master/"

def custom_doc_links(name): return None
