# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['read']

# Cell
import toml

# Cell
def read(wcsfile: str) -> dict:
    "Read WCS (key,value) pairs from DS9's *.wcs files"
    with open(wcsfile) as stream:
        return toml.loads(_fixups(stream.read()))

# Cell
def _fixups(s: str) -> str:
    "Apply fixes to WCS file syntax to make it valid TOML"
    s = s.replace("0.\n", "0.0\n")
    return s