#+LINK: viewnb elisp:(view-file-other-window "../notebooks/ngc346-orig/%s")

[[viewnb:01-00-line-ratios.py]]
[[viewnb:01-01-more-line-ratios.py]]
[[viewnb:01-02-yet-more-line-ratios.py]]

This is a continuation of the work done in [[file:bow-pz-maps.org]], which made all the new maps from the PZ cube.

* Calculate line ratios from the new "refined" emission maps and spectra
- This is going to be a partial re-run of all that I did in the notebooks such as
  - [[file:../notebooks/ngc346-orig/01-00-line-ratios.py]]
    Mainly [S II] ratios
  - [[file:../notebooks/ngc346-orig/01-01-more-line-ratios.py]]
  - [[file:../notebooks/ngc346-orig/01-02-yet-more-line-ratios.py]]
- Question is, do I want to do it in notebooks, or here in this org file with some scripts
  - Notebooks might be easier, but it might be better to split it up into smaller parts
  - Although the easiest thing to do to start with is to just run them as is. 

    
** TODO Rerun of the PZ-01-*.ipynb as ZZ-01-*.ipynb
:LOGBOOK:
- Note taken on [2024-07-25 Thu 12:30] \\
  Return to this after an absence. I cannot remember what it was that made me stop doing this.
:END:
- [X] Copy the .py files to the new folder [[file:../notebooks/ngc346-bow/]] and rename them with ZZ prefix
- [X] Regenerate the notebook files with jupytext
  #+begin_src sh :dir ../notebooks/ngc346-bow/ :eval no
    jupytext --show-changes --sync *.py
  #+end_src
  Note that the ~-d~ option has changed to ~--show-changes~
  
*** Look at the [S II] line ratios
:LOGBOOK:
- Note taken on [2025-10-17 Fri 08:59] \\
  Trying to pick up this work where it was abandoned
:END:
- Going through the initial part of the first notebook
  - I loaded the median-subtracted cube and followed the same steps, except that I did not subtract the continuum, since that has already been done
- These worked better with the full extraction of a wide window than they did with the 3 wave images, which is a bit annoying
- Except, I suspect that this can be fixed by using the ... what?
  - [2025-10-17 Fri 09:01] This sentence was never finished, annoyingly
    - Possibly I was going to say that it was using the flux correction from the 3-wave method
    - However, we do not necessarily have time for that now

*** The remaining notebooks
- It looks like we have the following from July 2024
  - [[file:../notebooks/ngc346-bow/ZZ-01-00-line-ratios.ipynb]]
  - [[file:../notebooks/ngc346-bow/ZZ-01-01-more-line-ratios.ipynb]]
- These are re-running the analysis of line ratios using the Peter cubes and (I think) the 3-wave results
- The results for the [Ar IV] density and temperature seem worse than for the original ESO cubes, in the sense that the 4711/4740 ratio is outside the allowed range
  - [ ] I do not know if this is due to the missing flux correction or what
- We do not seem to have an equivalent of the [[viewnb:01-02-yet-more-line-ratios.py]] notebook in either the PZ or the ZZ series
  - [ ] Is this important?
